run:
  timeout: 100s
  allow-parallel-runners: true

issues:
  exclude-rules:
    - path-except: modules/*/infrastructure/persistence/*mappers.go
      linters:
        - exhaustive
        - exhaustruct
    - path-except: modules/*/domain/*/*/*.go
      linters:
        - exhaustive
        - exhaustruct
  exclude-files:
    - pkg/graphql/graphql.go
  exclude-dirs:
    - pkg/fp

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    #    - containedctx
    #    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    #    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - exhaustruct
    - fatcontext
    - forbidigo
    #    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    #    - gocognit
    #    - goconst
    - gocyclo
    #    - godot
    - gofmt
    #    - gofumpt
    - goheader
    #    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    #    - intrange
    #    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    #    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    #    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    #    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    #    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
