project_name: my-project

release:
  # Automatically create a GitHub release
  github:
    owner: iota-agency
    name: iota-sdk

builds: [ ] # No binaries to build

archives:
  - id: source-archive
    format: tar.gz
    files:
      - "**/*"  # Include all source files

changelog:
  use: git
  sort: asc
