services:
  db:
    image: postgres:15.1
    restart: always
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr", "-c", "logging_collector=off" ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iota_erp
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      DB_NAME: iota_erp
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: password
      DOMAIN: localhost
      SESSION_DURATION: 720h

