version: '3.8'

services:
  erp:
    restart: always
    build:
      context: .
      target: staging
    environment:
      GO_APP_ENV: production
      DB_NAME: iota_erp
      DB_HOST: ${COMMIT_SHA}-erp_db
      DB_PORT: 5432
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DOMAIN: erp.ci.iota.uz
      SESSION_DURATION: 720h
      GOOGLE_CLIENT_ID: 1234567890.apps.googleusercontent.com # TODO: Change this
      GOOGLE_CLIENT_SECRET: 123456789
      GOOGLE_REDIRECT_URL: https://erp.ci.iota.uz/auth/google/callback
      OPENAI_KEY: sk-1234567890 # TODO: Change this
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMMIT_SHA}-erp.rule=Host(`erp.ci.iota.uz`)"
      - "traefik.http.routers.${COMMIT_SHA}-erp.tls=true"
      - "traefik.http.routers.${COMMIT_SHA}-erp.tls.certresolver=letsencrypt"
      - "traefik.http.services.${COMMIT_SHA}-erp.loadbalancer.server.port=3200"
      - "traefik.http.routers.${COMMIT_SHA}-erp.tls.domains[0].main=iota.uz"
      - "traefik.http.routers.${COMMIT_SHA}-erp.tls.domains[0].sans=*.ci.iota.uz"
    depends_on:
      - erp_db
    networks:
      - app

  erp_db:
    image: postgres:15.1
    restart: always
    hostname: ${COMMIT_SHA}-erp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: iota_erp
    volumes:
      - ~/volumes/iota_sdk/postgres/data:/var/lib/postgresql/data
    ports:
      - "17889:5432"
    networks:
      - app

networks:
  app:
    name: app
    external: true
