development:
  dialect: postgres
  datasource: dbname=iota_erp sslmode=disable user=postgres password=postgres
  dir: migrations/postgres
  table: migrations

staging:
  dialect: postgres
  datasource: dbname=iota_erp sslmode=disable user=postgres password=2dP9L9d6gB9597 host=erp_db
  dir: migrations/postgres
  table: migrations

production:
  dialect: postgres
  datasource: dbname=iota_erp sslmode=disable user=${DB_USER} password=${DB_PASSWORD} host=${DB_HOST}
  dir: migrations/postgres
  table: migrations
