name: Deployment

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: 'gcidp'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build and Deploy
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_SHA: ${{ github.sha }}
        run: docker compose -f compose.staging.yml up -d --build

