on:
  push:
    branches:
      - staging
    paths:
      - '**/*.sql'

jobs:
  migrations_redo:
    runs-on: gcidp
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Migrate Redo
        run: |
          echo "Detected .sql file changes. Running 'migrate redo'..."
          docker compose -f compose.staging.yml run --rm erp go run cmd/migrate/main.go redo

