name: Test, lint & build

on:
  - push

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.2"

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0
          golangci-lint version

      - name: Install templ
        run: |
          go install github.com/a-h/templ/cmd/templ@v0.2.793
          templ --help

      - name: Download Go dependencies
        run: |
          go mod download

      - name: Generate templates and run go vet
        run: |
          templ generate
          git diff --exit-code
          go vet ./...
          go test -v ./...
