name: Test, lint & build

on:
  - push

jobs:
  lint:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: useblacksmith/setup-go@v6
        with:
          go-version: "1.23.2"

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b "$(go env GOPATH)/bin" v1.61.0

      - name: Install templ
        run: |
          go install github.com/a-h/templ/cmd/templ@v0.3.819

      - name: Install TailwindCSS
        run: |
          mkdir -p downloaded
          curl -sL -o downloaded/tailwindcss \
            https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.15/tailwindcss-linux-x64
          chmod +x downloaded/tailwindcss
          echo "$PWD/downloaded" >> $GITHUB_PATH

      - name: Verify TailwindCSS
        run: tailwindcss -h

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Go mod download
        run: go mod download

      - name: Check generated files
        run: |
          make generate
          git diff --exit-code

      - name: Custom linter
        run: |
          make build-iota-linter
          make run-iota-linter

      - name: Format SQL
        run: |
          sudo apt-get update
          sudo apt-get install -y pgformatter
          mkdir -p /tmp/formatted
          find modules -name "*.sql" -type f | while read -r f; do
            pg_format "$f" > "/tmp/formatted/$(basename "$f")"
            diff -q "$f" "/tmp/formatted/$(basename "$f")" || exit 1
          done

      - name: Migrations collect
        run: |
          make migrate collect
          if [ -n "$(git status --porcelain migrations/)" ]; then
            exit 1
          fi

      - name: Build CSS
        run: make css

  test:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    services:
      postgres:
        image: postgres:15.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: iota_erp
        ports:
          - 5432:5432
        options: >-
          --hostname=erp_db
          --health-cmd="pg_isready -U postgres -d iota_erp"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: useblacksmith/setup-go@v6
        with:
          go-version: "1.23.2"

      - name: Go mod download
        run: go mod download

      - name: Install templ
        run: |
          go install github.com/a-h/templ/cmd/templ@v0.3.819

      - name: Install TailwindCSS
        run: |
          mkdir -p downloaded
          curl -sL -o downloaded/tailwindcss \
            https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.15/tailwindcss-linux-x64
          chmod +x downloaded/tailwindcss
          echo "$PWD/downloaded" >> $GITHUB_PATH

      - name: Verify TailwindCSS
        run: tailwindcss -h

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U postgres -d iota_erp; do
            sleep 1
          done

      - name: Test Make targets
        # Run the same target twice to ensure idempotency
        run: |
          make migrate up
          make migrate up
          make seed
          make seed

      - name: Go vet & tests
        run: |
          make generate
          git diff --exit-code
          go vet ./...
          go test -v ./...

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          SESSION_DURATION: 720h
          DOMAIN: localhost
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: iota_erp
          DB_USER: postgres
          DB_PASSWORD: postgres
          SID_COOKIE_KEY: sid
          GO_APP_ENV: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          record: true
          working-directory: e2e
          install-command: pnpm install
          start: go run ../cmd/server/main.go
          wait-on: 'http://localhost:3200'
          browser: chrome

      - name: Migrate down
        run: make migrate down

